services:
  chrome:
    image: selenium/node-chrome:4.21.0
    shm_size: 2gb
    volumes:
      - .:/usr/src/app
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    profiles:
      - chrome

  firefox:
    image: selenium/node-firefox:4.21.0
    shm_size: 2gb
    volumes:
      - .:/usr/src/app
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    profiles:
      - firefox

  selenium-hub:
    image: selenium/hub:4.21.0
    ports:
      - "4444:4444"

  selenium-tests:
    build: .
    image: selenium-tests:latest
    depends_on:
      - selenium-hub
    environment:
      - BASE_URL=${BASE_URL:-}
      - BROWSER=${BROWSER:-CHROME_REMOTE}